Fix error when zip_code is wrong
hqrEdu/ZeroToJuniorMapAlpha pull request #40
Opened 2023-03-06 11:55 UTC by andrzejstopka

2023-03-06 14:43 UTC, bartoszkobylinski requested changes

2023-03-06 14:43 UTC, bartoszkobylinski commented on backend/utility_functions/geolocation.py
>      postcode = zip
a czemu tutaj jest utworzona zmienna postcode, w funkcji przekazujesz jako argument, ktory od razu przekazujesz do 
location = geolocator.geocode(zip,....

Stworzenie nowej zmiennej jest tylko marnowaniem zasobow. Jesli chcialbys lepiej to nazwac to zamiast zip nazwij to postcode od razu.

2023-03-06 15:30 UTC, andrzejstopka commented on backend/utility_functions/geolocation.py
>      postcode = zip
Done 61a3c80d24677b8df0d0a2f1adf7cdbe041f3021

2023-03-22 16:54 UTC, bartoszkobylinski commented on backend/utility_functions/geolocation.py
> +        if location.raw["address"].get("city"):
a co sie stanie jesli location bedzie ale 
location.raw['address'] bedzie mial wartosc None ? 
Wtedy wywali sie i rzuci argumentem Key not exist
Jesli to jest slownik to jest na to funkcja wbudowana w slownikach, ktora zabezpiecza wyrzucenie Erroru i dodatkowo daje mozliwosc trackowanie czy tak sie stalo.

2023-03-22 18:17 UTC, andrzejstopka commented on backend/utility_functions/geolocation.py
> +        if location.raw["address"].get("city"):
A po którym commicie sprawdzałeś? Bo w tym co dzisiaj wrzuciłem właśnie usunąłem taką możliwość

2023-03-22 21:15 UTC, bartoszkobylinski commented on backend/utility_functions/geolocation.py
> +        if location.raw["address"].get("city"):
Nie wiem.
chodzi mi o to czy nie lepiej bedzie, uzyc metody get
city = location.get("address", "address not found").get("town", "town not found")
wtedy jesli nie ma "klucza" to masz informacje a nie wywala erroru. Nie wiem tylko czy location jest wlasnym typem czy dict.

2023-03-23 09:21 UTC, andrzejstopka commented on backend/utility_functions/geolocation.py
> +        if location.raw["address"].get("city"):
29b2214c8215138dd6bb5f39185d2c0902f8e846
Rzuć okiem na to, jeśli nie zostanie znalezione miasto przy przypisywaniu wartości location, to nie będzie erroru tylko location będzie miało None. Więc później jest blok ifów elifów i jeśli one nie będą istniały to zadziała else raise Value które zostanie obsłużone przez error_handler w app i zwróci bad request do użytkownika. Wydaję mi się, że nie ma sensu kombinować i tego zmieniać...

2023-04-02 05:52 UTC, Hankier approved these changes

2023-04-02 05:57 UTC, merged