Error handling with APIException
hqrEdu/ZeroToJuniorMapAlpha pull request #59
Opened 2023-04-05 11:26 UTC by andrzejstopka

2023-04-05 15:14 UTC, Hankier commented on backend/utility_functions/api_exceptions.py
> +    status_code = 404
Change to 400

2023-04-05 15:15 UTC, Hankier commented on backend/requirements.txt
> +flask_api = 3.0.post1
Is that proper format?

2023-04-05 15:16 UTC, Hankier requested changes
Change status code and check requiremnts file format.

2023-04-05 18:24 UTC, andrzejstopka commented on backend/utility_functions/api_exceptions.py
> +    status_code = 404
4b38fb4e01bb4e3742f60b1891f7fd85a616f477 Done

2023-04-05 18:25 UTC, andrzejstopka commented on backend/requirements.txt
> +flask_api = 3.0.post1
4b38fb4e01bb4e3742f60b1891f7fd85a616f477 Done

2023-04-11 10:47 UTC, Hankier approved these changes

2023-04-11 19:25 UTC, merged